language: node_js
node_js:
  - "10.12.0"

install:
  - npm i -g yarn && yarn

script:
  - /bin/sh .travis.sh

# Only build pushes to master branch, prevents duplicate jobs in PRs
branches:
  only: 
    - master